// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGv71Sp-lq9qtHOUxlSQIa5xp34CkxyU0',
    appId: '1:729169504213:android:0a3928a838c904c42dff5c',
    messagingSenderId: '729169504213',
    projectId: 'ecommerceapp-7b68b',
    storageBucket: 'ecommerceapp-7b68b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgaOYdkW5jrmZNEDQNvfPP3cbINatqtxw',
    appId: '1:729169504213:ios:b65fd08fd230b3942dff5c',
    messagingSenderId: '729169504213',
    projectId: 'ecommerceapp-7b68b',
    storageBucket: 'ecommerceapp-7b68b.appspot.com',
    androidClientId: '729169504213-n1gkpjtb85lr5dgjv965424t72876dfb.apps.googleusercontent.com',
    iosClientId: '729169504213-nonueqiiedhj67nkajc8hbvcsl67p67d.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMoi',
  );
}
